<?php

declare(strict_types=1);

namespace OpenEuropa\TaskRunner\Commands;

/**
 * Class Drupal8Commands.
 */
class Drupal8Commands extends AbstractDrupalCommands
{
    /**
     * @param string $settings_override_filename
     *
     * @return string
     */
    protected function getSettingsSetupAddendum($settings_override_filename)
    {
        return <<< EOF
/**
 * Include Drupal 8 settings overrides.
 *
 * The following file is generated by the openeuropa/task-runner project
 * using configuration from your local "runner.yml.dist/runner.yml" files.
 *
 * Keep this code block at the end of the file.
 */
if (file_exists(\$app_root . '/' . \$site_path . '/$settings_override_filename')) {
  include \$app_root . '/' . \$site_path . '/$settings_override_filename';
}
EOF;
    }
}
