<?php

namespace OpenEuropa\TaskRunner\Commands;

/**
 * Class Drupal8Commands.
 */
class Drupal8Commands extends AbstractDrupalCommands
{
    /**
     * @param string $settings_override_filename
     *
     * @return string
     */
    protected function getSettingsSetupAddendum($settings_override_filename)
    {
        return <<< EOF
/**
 * Include Drupal 8 settings overrides.
 *
 * The following file is generated by the openeuropa/task-runner project
 * using configuration from your local "runner.yml.dist/runner.yml" files.
 *
 * Keep this code block at the end of the file.
 */
if (file_exists(\$app_root . '/' . \$site_path . '/$settings_override_filename')) {
  include \$app_root . '/' . \$site_path . '/$settings_override_filename';
}
EOF;
    }

    /**
     * @return string
     */
    protected function getSettingsLocalSetupAddendum()
    {
        return <<< EOF

/**
 * Load local development override configuration, if available.
 */
if (file_exists(\$app_root . '/' . \$site_path . '/settings.local.php')) {
  include \$app_root . '/' . \$site_path . '/settings.local.php';
}
EOF;
    }

    /**
     * @param array $options
     *
     * @return string|false The default path for local settings or false if it doesn't exist.
     */
    protected function getLocalSettingsPath(array $options)
    {
        return $options['root'] . '/sites/' . $options['sites-subdir'] . '/settings.local.php';
    }
}
