# =============================================================================
# Default Task Runner configuration
# =============================================================================

# -----------------------------------------------------------------------------
# Global Task Runner settings
# -----------------------------------------------------------------------------
#
# The "runner.working_dir" will contain the full path to current working directory.
# @see OpenEuropa\TaskRunner\TaskRunner::createConfiguration()
runner:
  bin_dir: "./vendor/bin"
#  working_dir: ~

# -----------------------------------------------------------------------------
# Drupal-related settings.
# -----------------------------------------------------------------------------
#
# Value of "drupal.root_absolute" is derived at runtime.
# @see OpenEuropa\TaskRunner\Commands\DrupalCommands::setRuntimeConfig()
drupal:
  core: 9
  root: "build"
  root_absolute: ~
  base_url: "http://127.0.0.1:8888"

  # Basic Drupal site information.
  site:
    name: "Site name"
    mail: "info@example.org"
    profile: "standard"
    update: "false"
    locale: "en"
    sites_subdir: "default"
    # The "drupal.site.config_dir" option is deprecated. For Drupal 8.6 and
    # higher, use "drupal.site.existing_config" instead.
    config_dir: ~
    existing_config: false
    settings_override_file: "settings.override.php"
    # Setting this to "false" will run "site-install" without the "--db-url" parameter.
    # This is useful if the database settings are already set in your settings.php file.
    generate_db_url: true
    # By setting this to NULL, will disable the update status module option
    # (install_configure_form.enable_update_status_module) during "site-install" execution. By default is TRUE.
    update_status_module: "true"
    # By setting this to NULL, will disable the update status emails option
    # (install_configure_form.enable_update_status_emails) during "site-install" execution. By default is TRUE.
    update_status_emails: "true"

  # Administrator account information.
  account:
    name: "admin"
    password: "admin"
    mail: "admin@example.org"

  # Database settings.
  database:
    # @deprecated
    # The "type" option will be removed in version 1.0.0. Use "scheme".
    type: ""
    scheme: "mysql"
    host: "127.0.0.1"
    port: "3306"
    name: ""
    user: ""
    password: ""

  # Config example for sqlite usage.
  # Note that empty strings should be used to override default settings.
  #    database:
  #      scheme: "sqlite"
  #      host: "/path/to/my/database"
  #      port: ""
  #      name: "database.sqlite"
  #      user: ""
  #      password: ""

  # Local Drush settings file will be generated by following default values.
  drush:
    options:
      uri: "${drupal.base_url}"

  # Following lines will be converted in PHP and appended to default.settings.php.
  settings: []

  # List of shell commands to be before and after the site installation.
  # You can use same syntax as the "commands:", check the documentation for more.
  # Configuration token replacement is supported too.
  pre_install: []
  post_install: []

# -----------------------------------------------------------------------------
# GitHub configuration values.
# -----------------------------------------------------------------------------
github:
  # GitHub personal access token token.
  # @link https://github.com/settings/tokens
  token: ~

# -----------------------------------------------------------------------------
# Release commands configuration values.
# -----------------------------------------------------------------------------
release:

  # List of tasks to be ran before creating the release archive.
  tasks: []

  # Time and date formats used when generating values below.
  time_format: "H:i:s"
  date_format: "Y-m-d"

  # The following values are created at runtime and can be used when appending
  # release notes to text files.
  # They can be accessed via ${release.NAME}
# version: ~
# date: ~
# time: ~
# timestamp: ~

# -----------------------------------------------------------------------------
# List of dynamically-defined commands.
# -----------------------------------------------------------------------------
commands: []
